on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: Test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version:
          - 1.16.x
          - 1.15.x
          - 1.14.x
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...